<Project>
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <WarningsNotAsErrors>WPF0001</WarningsNotAsErrors>
    <Deterministic>true</Deterministic>
    <Version>1.1.10</Version>
    <AssemblyVersion>1.1.10.0</AssemblyVersion>
    <FileVersion>1.1.10.0</FileVersion>
    <InformationalVersion>1.1.10</InformationalVersion>
  </PropertyGroup>
</Project>
